// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package mock_my_assets_service is a generated GoMock package.
package mock_my_assets_service

import (
	context "context"
	reflect "reflect"

	shared "github.com/dacharat/my-crypto-assets/pkg/shared"
	gomock "github.com/golang/mock/gomock"
)

// MockIMyAssetsService is a mock of IMyAssetsService interface.
type MockIMyAssetsService struct {
	ctrl     *gomock.Controller
	recorder *MockIMyAssetsServiceMockRecorder
}

// MockIMyAssetsServiceMockRecorder is the mock recorder for MockIMyAssetsService.
type MockIMyAssetsServiceMockRecorder struct {
	mock *MockIMyAssetsService
}

// NewMockIMyAssetsService creates a new mock instance.
func NewMockIMyAssetsService(ctrl *gomock.Controller) *MockIMyAssetsService {
	mock := &MockIMyAssetsService{ctrl: ctrl}
	mock.recorder = &MockIMyAssetsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMyAssetsService) EXPECT() *MockIMyAssetsServiceMockRecorder {
	return m.recorder
}

// GetAllAssets mocks base method.
func (m *MockIMyAssetsService) GetAllAssets(ctx context.Context) ([]shared.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAssets", ctx)
	ret0, _ := ret[0].([]shared.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAssets indicates an expected call of GetAllAssets.
func (mr *MockIMyAssetsServiceMockRecorder) GetAllAssets(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAssets", reflect.TypeOf((*MockIMyAssetsService)(nil).GetAllAssets), ctx)
}

// GetAssetByPlatform mocks base method.
func (m *MockIMyAssetsService) GetAssetByPlatform(ctx context.Context, platform shared.Platform) (shared.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetByPlatform", ctx, platform)
	ret0, _ := ret[0].(shared.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetByPlatform indicates an expected call of GetAssetByPlatform.
func (mr *MockIMyAssetsServiceMockRecorder) GetAssetByPlatform(ctx, platform interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetByPlatform", reflect.TypeOf((*MockIMyAssetsService)(nil).GetAssetByPlatform), ctx, platform)
}
